4.8. Покоритель баз данных
htmlacademy-nodejs-api/780933-six-cities-simple-2 pull request #5
Opened 2022-09-28 01:24 UTC by Kaputin

2022-09-28 17:20 UTC, Razzwan requested changes

2022-09-28 17:20 UTC, Razzwan commented on docker-compose.yml
> +      MONGO_INITDB_ROOT_PASSWORD: test
Здесь желательно использовать данные из .env для этого есть директива `env_file:`

2022-09-28 17:20 UTC, Razzwan commented on docker-compose.yml
> +      ME_CONFIG_MONGODB_ADMINPASSWORD: test
Здесь желательно использовать данные из .env для этого есть директива env_file:

2022-09-28 17:20 UTC, Razzwan commented on package.json
> +    "mongoose": "^6.6.2",
Лучше конкретная версия без птички. В одном из предыдущих курсов объяснялось, почему (исправлять не обязательно, но можем обсудить при желании)

2022-09-28 17:20 UTC, Razzwan commented on src/cli-command/import-command.ts
> +const DEFAULT_DB_PORT = 27017;
Если следовать букве проекта, эти данные должны быть в конфиге, в поле `PORT`

2022-09-28 17:20 UTC, Razzwan commented on src/cli-command/import-command.ts
> +    this.logger = new ConsoleLoggerService();
Сравни этот код с примером: мы должны прокидывать зависимости в конструктор, используя паттерн "инъекция зависимостей". Для этого мы подключили библиотеку "import {inject, injectable} from 'inversify';"

Это называется "инверсия зависимостей". Можем обсудить при желании

2022-09-28 17:20 UTC, Razzwan commented on src/common/config/config.schema.ts
> +    default: 27017,
Вот здесь же мы уже указали дефолтное значение для порта

2022-09-28 17:20 UTC, Razzwan commented on src/common/config/config.schema.ts
> +    default: 'course-nodejs-restapi'
Откуда взял это значение? Рекоммендую оставлять это поле пустым. Так мы увидим более "говорящую" ошибку в случае, если забудем указать имя базы данных в конфиге

2022-09-28 17:20 UTC, Razzwan commented on src/common/database-client/database.service.ts
> +    this.logger.info('Try to connect to MongoDB…');
Нужно удалить. Попытка должна быть успешной. Есть смысл извещать об успехе, но нет смысла информировать о попытке. Если попытка будет неудачной - мы увидимо ошибку в логах

2022-09-28 17:20 UTC, Razzwan commented on src/modules/user/user.entity.ts
> +  public password!: string;
Я бы воздержался от задания пароля по-умолчанию в виде пустой строки. Это может нас ввести в заблуждение и позволять сохранять пользователей с пустыми паролями

2022-10-05 23:53 UTC, Kaputin commented on package.json
> +    "mongoose": "^6.6.2",
зачем знаю, критерия просто не было) переделаю если сломается что

2022-10-06 10:35 UTC, merged